import { config } from 'dotenv';
config();

export const CREDENTIALS = process.env.CREDENTIALS === 'true';

export const {
  PORT,
  ORIGIN,
  DATABASE_URL,
  NODE_ENV,
  APP_SECRET,
  HOST,
  JWT_SECRET_KEY,
  JWT_ACCESS_TOKEN_EXPIRE_HOURS,
  API_DOMAIN,
  API_VERSION,
  /* CLD CONFIG */
  CLD_API_KEY,
  CLD_API_SECRET,
  CLD_CLOUD_NAME,
  /* GETSTREAM.IO CONFIG */
  GETSTREAM_API_KEY,
  GETSTREAM_API_SECRET,
  GETSTREAM_WEBHOOK_URL,
  /* VNPAY CONFIG*/
  VNP_TMNCODE,
  VNP_HASHSECRET,
  VNP_COMMAND,
  VNPAY_SANDBOX_HOST,
  VNPAY_ENDPOINT,
  VNPAY_RETURN_URL,
  VNPAY_TEST_MODE,
  VNPAY_MODE,
  VNP_VERSION,
  /* FIREBASE */
  FIREBASE_CLOUD_MESSAGE_CERTIFICATION,
  /* EMAIL */
  EMAIL_SERVICE,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASSWORD,
  EMAIL_FROM,
  EMAIL_VERIFY_URL,
} = process.env;
